{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
  {{- if .service.annotations }}
  annotations:
  {{- toYaml .service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .service.type | default "ClusterIP" }}
  selector:
    app: {{ .name }}
  ports:
  - name: http
    port: {{ .port }}
    targetPort: {{ .port }}
{{- end }}
