# Global defaults
replicaCount: 2

services:
  - name: frontend
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.3
    port: 8080
    replicas: 2
    service:
      type: LoadBalancer
      annotations: {}
    env:
      - name: PORT
        value: "8080"
      - name: ENV_PLATFORM
        value: "local"
  - name: emailservice
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.3
    port: 8080
    replicas: 1
    service:
      type: ClusterIP
      annotations: {}
    env:
      - name: PORT
        value: "8080"
  - name: checkoutservice
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
    port: 5050
    replicas: 2
    service:
      type: ClusterIP
      annotations: {}
    env:
      - name: PORT
        value: "5050"
  # Add more services as needed
